@url = http://localhost:3615

### BASE
GET {{url}}

### ALL EMPLOYEES
GET {{url}}/employees

### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"lastName": "Addington",
	"firstName": "Arthor",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}

### DELETE EMPLOYEE
DELETE {{url}}/employee/63be1174bbc54eede15136c7

### EDIT EMPLOYEE
PUT {{url}}/employee/63be1174bbc54eede15136c7
content-type: application/json

{
	"lastName": "CHANGED-LAST-NAME",
	"firstName": "CHANGED-FIRST-NAME",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}