@url = http://localhost:3615

### BASE
GET {{url}}

### ALL EMPLOYEES
GET {{url}}/employees

### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"lastName": "Addington",
	"firstName": "Author",
	"title": "Sales Representative",
	"notes": "Author is a test employee that we are adding."
}